ARCHS = arm64
include $(THEOS)/makefiles/common.mk

TOOL_NAME = CSStashedAppExecutable
CSStashedAppExecutable_FILES = main.m
CSStashedAppExecutable_INSTALL_PATH=/usr/local/bin

include $(THEOS_MAKE_PATH)/tool.mk
